language: java
jdk: oraclejdk8

install: gradle wrapper --gradle-version 5.0

addons:
  sonarcloud:
    organization: "due-info-ag-app"
    token:
      secure: ${SONAR_TOKEN}
android:
  components:
  - tools
  - platform-tools

  # The BuildTools version used by your project
  - build-tools-26.0.2

  # The SDK version used to compile your project
  - android-28
script:
- gradle assemble
- gradle check
- sonar-scanner

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

notifications:
email: false